<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'NS\\ABCPApi\\' => array($vendorDir . '/nodasoft/abcp_api_client/src'),
);
