<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'RestClient' => array($vendorDir . '/jowy/rest-client/src'),
);
